name: Build Vue
on: [push]
jobs:
  build_vue:
    runs-on: ubuntu-latest
    name: Build Vue
    steps:
    - uses: pnpm/action-setup@v2.1.0
      with:
        version: 6.0.2
    - uses: actions/checkout@v2
    - id: Build-Vue
      uses: ravensiris/VuePagesAction@main
      with:
        username: 'ravensiris'
        reponame: 'librelibrus'
        branch: 'v2'
        usepnpm: true
        token: ${{ secrets.GITHUB_TOKEN }} # Leave this line unchanged